# Numpy (NumericPy
Matematik biliminde çoğu işlemi yapabilen hazır fonk sahiptir. Numerik işlemleri hızlı yapabilen bir kütüphane.


In [3]:
import numpy as np

In [2]:
np.__version__

'1.21.6'

# Numpy Dizileri (ndarray)
N-Dimensional Array

In [3]:
py_list = [1,2,3,4,5]
np_array = np.array([6,7,8,9,10])

py_list

[1, 2, 3, 4, 5]

In [4]:
np_array

array([ 6,  7,  8,  9, 10])

In [4]:
np_array3 = np.array([[1,2,3], [4,5,6]])
np_array3

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np_array3.shape

(2, 3)

In [6]:
np_array4 = np.array([[1,2,3], [3,4,5]])

In [7]:
np_array5 = np.array([[2,1],[5,3], [6,8]])

In [8]:
sum_arrays2 = np_array3 + np_array5

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [9]:
np_array3

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np_array6 = np.array([10,20,30])

In [11]:
np_array3 + np_array6

array([[11, 22, 33],
       [14, 25, 36]])

In [12]:
np_array4.shape

(2, 3)

In [14]:
np_array5.shape

(3, 2)

In [15]:
arr = np.array([1,2,3,4,5,6])

In [16]:
arr

array([1, 2, 3, 4, 5, 6])

In [17]:
arr.shape

(6,)

In [18]:
reshaped_arr = arr.reshape(3,2)

In [19]:
reshaped_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
reshaped_arr.shape

(3, 2)

In [21]:
arr2 = np.array([[1,2,3], [4,5,6]])

In [22]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
flattened_arr = arr2.reshape(-1)

In [24]:
flattened_arr

array([1, 2, 3, 4, 5, 6])

In [25]:
#Tensors
tensor_arr = np.array([
    [[1,2,3],[3,2,5]],
    [[4,5,6,],[6,7,8]],
    [[4,5,6,],[6,7,8]],
    [[4,5,6,],[6,7,8]]
])

tensor_arr

array([[[1, 2, 3],
        [3, 2, 5]],

       [[4, 5, 6],
        [6, 7, 8]],

       [[4, 5, 6],
        [6, 7, 8]],

       [[4, 5, 6],
        [6, 7, 8]]])

In [26]:
tensor_arr.shape

(4, 2, 3)

In [27]:
np.ndim(arr2)

2

In [28]:
np.ndim(arr)

1

In [29]:
arr

array([1, 2, 3, 4, 5, 6])

In [30]:
arr.T

array([1, 2, 3, 4, 5, 6])

In [31]:
arr2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
vector_2D = np.array([[1,2,3]])
vector_2D.shape

(1, 3)

In [34]:
vector_2D.T.shape

(3, 1)